### ISSUE TITLE
Additional Macro

### ISSUE THREAD

**Issue by ParadaCarleton** [jonniedie/ConcreteStructs.jl#10]
@mohammed82008 built this nice macro for defining concrete structs that respect user parameters here:
https://github.com/JuliaNonconvex/NonconvexCore.jl/blob/master/src/utilities/params.jl

Do you guys think it'd be worth it to move the code for it here? I think `@params` is fairly generic, so I'd suggest keeping up the pattern with `@cement`.

**Comment by ParadaCarleton** [comment]
Nice, thanks! I too would like an excuse to make a cement macro, which is 80% of why I proposed this.

@mohamed82008 Do you know of anything else `@params` does that `@concrete` doesn't, or can I close this issue?

**Comment by mohamed82008** [comment]
>or can I close this issue?

Looks like you can close this issue :)
