### ISSUE TITLE
Accomodate field documentation

### ISSUE THREAD

**Issue by sdewaele** [jonniedie/ConcreteStructs.jl#6]
Thanks for this package - it is very useful!

It would be great if the package would handle docstrings for field names, like so:

```julia
@concrete struct MyStruct
    "my field documentation"
    a
end
```
Currently, this results in an error:
```julia
ERROR: LoadError: MethodError: no method matching _parse_line(::String)
```
```

**Comment by jonniedie** [comment]
Oh that should be a pretty easy fix. Actually, I’m not sure why I didn’t put a fallback implementation of `_parse_line` for stuff like this. I don’t have a computer on me for the weekend, so if you are feeling adventurous, feel free to submit a pull request. If not, I’ll take care of it when I get back Monday.

**Comment by jonniedie** [comment]
Actually I just went ahead and did it on my phone. It was a pretty easy fix

**Comment by sdewaele** [comment]
Thanks a lot, that was fast!
