### ISSUE TITLE
Revise error `invalid redefinition of constant MyType` for unchanged type

### ISSUE THREAD

**Issue by sdewaele** [jonniedie/ConcreteStructs.jl#8]
I am experiencing interference between `ConcreteStructs` and revise. When I have a type `MyType` defined in a file, and I change a different part of the file (i.e., `MyType` is unchanged), I get the revise error: `ERROR: invalid redefinition of constant MyType`.

**Comment by jonniedie** [comment]
Hm. I’ll try to give that a look this weekend. Thanks for catching this.

**Comment by jonniedie** [comment]
Since I was using `gensym` to generate names for the type annotations, it would change those names every time the file was reran. Even though this is functionally not changing the `struct` definition, Revise interpreted it as a change.

**Comment by sdewaele** [comment]
Thanks for the quick fix! This really facilitates the usage of ConcreteStucts+Revise.
